raghavapp/urls.py
from django.urls import path
from .views import * 
from . import views

app_name = 'raghavapp'
urlpatterns =[
	path('',HomeView.as_view(),name='home'),
	path('signup/',SignupFormView.as_view(),name="signup"),
	path('login/',LoginFormView.as_view(),name="login"),
	path('logout/',LogoutView.as_view(),name="logout"),
	path('profile/',BlogCreateView.as_view(),name='profile'),
	path('bloglist/',BloglistView.as_view(),name='bloglist'),
	path('blog/<int:pk>/update/',BlogUpdateView.as_view(),name='blogupdate'),
	path("forgot-password/", PasswordForgotView.as_view(), name="passworforgot"),
    path("password-reset/<email>/<token>/",
         PasswordResetView.as_view(), name="passwordreset"),
]

raghavpr/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('raghavapp.urls')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

raghavapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Profile(models.Model):
	name=models.CharField(max_length=200)
	image=models.ImageField(upload_to='Post', null=True, blank=True)
	address = models.CharField(max_length=200)
	contact = models.IntegerField()
	date=models.DateTimeField(default=datetime.now(), blank=None, null=None)

raghavapp/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from datetime import datetime


class SignupForm(forms.Form):
	username=forms.EmailField(widget=forms.EmailInput())
	password=forms.CharField(widget=forms.PasswordInput())
	confirm_password=forms.CharField(widget=forms.PasswordInput())
	class Meta:
		model = User
		fields = ['username','email','password','confirm_password']
	

class SendMailForm(forms.Form):
	recepient=forms.EmailField(widget=forms.EmailInput())
	subject=forms.CharField(widget=forms.TextInput())
	message=forms.CharField(widget=forms.Textarea())
class LoginForm(forms.Form):
	username=forms.EmailField(widget=forms.EmailInput())
	password=forms.CharField(widget=forms.PasswordInput())

class BlogCreateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields= ['name','image','address','contact']


class BlogUpdateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields= ['name','image','address','contact']

class PasswordForgotForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={
        "class": "form-control",
        "placeholder": "Enter the email used in customer account..."
    }))

    def clean_email(self):
        e = self.cleaned_data.get("email")
        print(e)
        if Profile.objects.filter(user__email=e).exists():
            pass
        else:
            raise forms.ValidationError(
                "Customer with this account does not exists..Plz enter valid email.")
        return e


class PasswordResetForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'new-password',
        'placeholder': 'Enter New Password',
    }), label="New Password")
    confirm_new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'new-password',
        'placeholder': 'Confirm New Password',
    }), label="Confirm New Password")

    def clean_confirm_new_password(self):
        new_password = self.cleaned_data.get("new_password")
        confirm_new_password = self.cleaned_data.get("confirm_new_password")
        if new_password != confirm_new_password:
            raise forms.ValidationError(
                "New Passwords did not match!")
        return confirm_new_password

raghavapp/views.py
from django.shortcuts import reverse ,redirect
from django.views.generic import * #TemplateView,ListView,DetailView,CreateView,UpdateView
from .models import *
from .forms import *
from django.urls import reverse_lazy
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate,login,logout
from django.core.mail import send_mail
from django.conf import settings

class HomeView(TemplateView):
	template_name = 'base.html'


class SignupFormView(FormView):
	template_name='signupform.html'
	form_class= SignupForm
	success_url=reverse_lazy('raghavapp:login')

	def form_valid(self,form):
		u_name=form.cleaned_data['username']
		p_word=form.cleaned_data['password']
		cp_word=form.cleaned_data['confirm_password']
		if p_word==cp_word:
			if User.objects.filter(username=u_name):
				return render(self.request,self.template_name,{
				'form':form,
				'error':"Email is already taken"})
			else:
				User.objects.create_user(username=u_name,password=p_word)
		else:
			return render(self.request,self.template_name,{
				'form':form,
				'error':"Password do not match"})

		return super().form_valid(form)


class LoginFormView(FormView):
	template_name='login.html'
	form_class=LoginForm
	success_url=reverse_lazy('raghavapp:bloglist')

	def get(self,request):
		if request.user.is_authenticated:
			return redirect('raghavapp:bloglist')
		return super().get(request)

	def form_valid(self,form):
		u_name=form.cleaned_data['username']
		p_word=form.cleaned_data['password']
		user=authenticate(username=u_name,password=p_word)
		if user is not None:
			login(self.request,user)
		else:
			return render(self.request,self.template_name,{'form':form,'error':"Invalid Candential"})
		return super().form_valid(form)

	def get_success_url(self,**kwargs):
		self.next_url=self.request.POST.get('next')
		if self.next_url is not None:
			return self.next_url
		else:
			return self.success_url


class LogoutView(View):
	def get(self,request):
		logout(request)
		return redirect('raghavapp:login')

class BlogCreateView(LoginRequiredMixin, CreateView):
	template_name= 'blogcreate.html'
	model = Profile
	form_class = BlogCreateForm
	success_url = reverse_lazy('raghavapp:home')

	def dispatch(self,request):
		if not request.user.is_authenticated:
			return redirect('raghavapp:login')
		return super().dispatch(request)

class BloglistView(LoginRequiredMixin, ListView):
	template_name = 'profile.html'
	queryset = Profile.objects.all()
	context_object_name = 'postlist'

class BlogUpdateView(UpdateView):
	template_name = 'profileupdate.html'
	model= Profile
	form_class = BlogUpdateForm
	success_url= '/bloglist/'


class PasswordForgotView(FormView):
    template_name = "forgotpassword.html"
    form_class = PasswordForgotForm
    success_url = "/forgot-password/?m=s"

    def form_valid(self, form):
        # get email from user
        email = form.cleaned_data.get("email")
        # get current host ip/domain
        url = self.request.META['HTTP_HOST']
        # get customer and then user
        customer = Customer.objects.get(user__email=email)
        user = customer.user
        # send mail to the user with email
        text_content = 'Please Click the link below to reset your password. '
        html_content = url + "/password-reset/" + email + \
            "/" + password_reset_token.make_token(user) + "/"
        send_mail(
            'Password Reset Link | Django Ecommerce',
            text_content + html_content,
            settings.EMAIL_HOST_USER,
            [email],
            fail_silently=False,
        )
        return super().form_valid(form)


class PasswordResetView(FormView):
    template_name = "passwordreset.html"
    form_class = PasswordResetForm
    success_url = "/login/"

    def dispatch(self, request, *args, **kwargs):
        email = self.kwargs.get("email")
        user = User.objects.get(email=email)
        token = self.kwargs.get("token")
        if user is not None and password_reset_token.check_token(user, token):
            pass
        else:
            return redirect(reverse("raghavapp:passworforgot") + "?m=e")

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        password = form.cleaned_data['new_password']
        email = self.kwargs.get("email")
        user = User.objects.get(email=email)
        user.set_password(password)
        user.save()
        return super().form_valid(form)
# Create your views here.

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Home</title>
</head>
<body>
  <a href="{% url 'raghavapp:home' %}">Home</a>
  {% if not request.user.is_authenticated %}
      <a href="{% url 'raghavapp:login' %}" class="w3-bar-item w3-button"><i class="fa fa-user-plus"></i>LOGIN</a>
      {% else %}
      <a href="{% url 'raghavapp:logout' %}" class="w3-bar-item w3-button"><i class="fa fa-user-plus"></i> LOGOUT</a>
      <a href="{% url 'raghavapp:bloglist' %}" class="w3-bar-item w3-button"><i class="fa fa-user-plus"></i> PROFILE</a>
      {% endif %}

</body>
</html>

templates/blogcreate.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>BlogCreate</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
	body {
  background-position: center;
  background-size: cover;
  background-image: url('{% static "img/login.jpg"%}');
  min-height: 100%;
  background-repeat: no-repeat;
}
.login-form {
    width: 340px;
    margin: 50px auto;
  	font-size: 15px;
}
.login-form form {
    margin-bottom: 15px;
    background: #f7f7f7;
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    padding: 30px;
}
.login-form h2 {
    margin: 0 0 15px;
}
.form-control, .btn {
    min-height: 38px;
    border-radius: 2px;
}
.btn {        
    font-size: 15px;
    font-weight: bold;
}
</style>
</head>
<body>
<div class="login-form">
       <h2 style="color: white;text-align: center;">Create New Post</h2>
  <form method="post" enctype="multipart/form-data">  <!-- Pic upload garana lai enctype ani vitra ko ab kura dinu parxa     -->
    {% csrf_token %}  <!-- YAsle encrypted form ma data pathau xa    -->
    {{form | crispy}}  <!-- KAsto type ko dekhnu xa ustai type ko aauxa like p vaneko paragraph ma aauxa ani table gate tabbular form maa aauxa ul garda paragraph ma aauxa tra dotted form ma -->
    </br>
    <center> 
    <button style="color: black;text-align: center;">Submit</button>
    </center>
    {% if error %}
    {{error}}
    {% endif %}
{{request.user.username}}
  </form>

</div>
</body>
</html>

templates/forgotpassword.html
<div class="w3l_banner_nav_right">
	<center>
            {% if request.GET.m == "s" %}
            <h3>Password reset link is sent to your email address. Please check your email immediately. </h3>
            {% else %}
            <h3>Enter your email used in making customer account to get password reset link</h3>
            {% if request.GET.m == "e" %}
            <h4 class="text-danger">Something went wrong, please enter your email again.</h4>
            {% endif %}
            <br>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <br>
                <button> Get Reset Link</button>
            </form>
            {% endif %}
    </center>

				<div class="clearfix"> </div>
			</div>
		</div>
<!-- //services -->
		</div>
		<div class="clearfix"></div>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Login</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
	body {
  background-position: center;
  background-size: cover;
  background-image: url('{% static "img/login.jpg"%}');
  min-height: 100%;
  background-repeat: no-repeat;
}
.login-form {
    width: 340px;
    margin: 50px auto;
  	font-size: 15px;
}
.login-form form {
    margin-bottom: 15px;
    background: #f7f7f7;
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    padding: 30px;
}
.login-form h2 {
    margin: 0 0 15px;
}
.form-control, .btn {
    min-height: 38px;
    border-radius: 2px;
}
.btn {        
    font-size: 15px;
    font-weight: bold;
}
</style>
</head>
<body>
<div class="login-form">
        <h2 class="text-center" style="color: white;">Log in</h2>       
        
     <form method="post" enctype="multipart/form-data"> 
    {% csrf_token %}  <!-- YAsle encrypted form ma data pathau xa    -->
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}

    {{form.as_p}} 
    <p align="center"><button style="color: black; border-radius: 25px;margin-left: 10px;">Login</button></p><br>
    {% if error %}
    {{error}}
    {% endif %}

    </form>

        <div class="clearfix">
            <label class="float-left form-check-label" style="color: blue;"><input type="checkbox"> Remember me</label>
        </div>        
    <p class="text-center"><a href="{% url 'raghavapp:signup' %}">Create an Account</a></p>
    <p><a href="{% url 'raghavapp:passworforgot' %}">Forgot your password?</a></p>
</div>
</body>
</html>

templates/passwordreset.html
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button>Reset password</button>
            </form>
        </div>
    </div>
</div>

templates/profile.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h2 style="text-align: center;color: green">Profile</h2>
	{% for post in postlist %}
	<h3 style="text-align: center;">{{post.id}}. {{post.name}}</h3>
	<h3 style="text-align: center;">Address: {{post.address}}</h3>
	<center>      <!-- |truncatechars:'10' le limited contexts dekhauxa -->
		{% if post.image %}<img src="{{post.image.url}}" style="width: 400px;height: 300px;">{% endif %}
			<h3>Contact: {{post.contact}}</h3>
</video>
		<h3>{{post.date}}</h3>
		<h2>{{post.posted_by}}</h2>
	</center>
		<!-- <h2>Comments:</h2><center> -->
		<!-- {% for comment in post.comment_set.all%} -->
		   <!-- post.comment ma hami le comment ko small letter liye ko xau kina vane yasto garda yastai small ma linu parxa -->
		<!-- <p>{{comment.comment}}</p> -->
		<!-- <h4>{{comment.commented_by}}</h4> -->
		<!-- <h5>{{comment.date}}</h5> -->
		<!-- {% endfor %} -->
		<!-- </center> -->  
		<!-- <a href="/blog/{{post.id}}/detail/">Read More</a>    -->
		<!-- Yo static url vayo tra hami lai dynamically linu parxa   -->
		<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width="" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div><br>
		 <!-- yasle blog detail ko link kholxa blohlist and blogdetail ko link yahi bata ho -->
		<a href="{% url 'raghavapp:blogupdate' post.id %}">Update Profile</a>

</body>
<script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpsh'},{'server':'p3plcpnl0769'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script><script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script>
</html>
	
		
	{% endfor %}

templates/profileupdate.html
{% load static %}



	<h2>Update</h2>
	<form method="post" enctype="multipart/form-data">  <!-- Pic upload garana lai enctype ani vitra ko ab kura dinu parxa     -->
		{% csrf_token %}  <!-- YAsle encrypted form ma data pathau xa    -->
		{{form.as_p}}   <!-- KAsto type ko dekhnu xa ustai type ko aauxa like p vaneko paragraph ma aauxa ani table gate tabbular form maa aauxa ul garda paragraph ma aauxa tra dotted form ma --> 
		<button style="color: blue">Update</button>

	</form>

templates/signupform.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Signup</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
	body {
  background-position: center;
  background-size: cover;
  background-image: url('{% static "img/signup.jpg"%}');
  min-height: 100%;
  background-repeat: no-repeat;
}

.login-form {
    width: 340px;
    margin: 50px auto;
  	font-size: 15px;
}
.login-form form {
    margin-bottom: 15px;
    background: #f7f7f7;
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    padding: 30px;
}
.login-form h2 {
    margin: 0 0 15px;
}
.form-control, .btn {
    min-height: 38px;
    border-radius: 2px;
}
.btn {        
    font-size: 15px;
    font-weight: bold;
}
</style>
</head>
<body>
<div class="login-form">
      	<center>
  <h2 style="color: black;">Signup Here</h2>
    <form method="post" enctype="multipart/form-data"> 
    {% csrf_token %}  <!-- YAsle encrypted form ma data pathau xa    -->
    {{form | crispy}}

    <button style="color: black;border-radius: 40px;margin-top: 10px;">Signup</button><br>
    {% if error %}
    {{error}}
    {% endif %}

    </form>
</center>

        <div class="clearfix">
            <label class="float-left form-check-label"><input type="checkbox"> Remember me</label>
        </div>        
    <p class="text-center"><a href="{% url 'raghavapp:login' %}" style="color: red;">I have an Account</a></p>
</div>
</body>
</html>